version: 0.0
os: linux 
files:
  - source: /
    destination: /var/mount/wyn.slack
hooks:
  ApplicationStart:
    - location: scripts/start_pm2
      timeout: 300
      runas: app
  ApplicationStop:
    - location: scripts/stop_pm2
      timeout: 300
      runas: app
